Summaries-generation-index
DEFRA/fcp-find-ai-frontend pull request #28
Opened 2024-07-12 14:01 UTC by StanHus

2024-07-15 12:18 UTC, StanHus commented
@MohammedFoysal, I test on Sustainable Farming Incentive because thats the only thing I have so far in the summaries index search. Example:
![Screenshot 2024-07-15 at 13 18 19](https://github.com/user-attachments/assets/8e26ff09-12bc-420b-8b57-f099c37f1476)

For now it sometimes spits out the wrong format (just text, no blocks) , is it an existing issue? Or did some of my changes cause it?

2024-07-15 13:01 UTC, MohammedFoysal requested changes

2024-07-15 13:01 UTC, MohammedFoysal commented on app/utils/langchain-utils.js
> +        error = true
You can return early here instead of setting a flag. `return []`

2024-07-15 15:47 UTC, StanHus commented
@MohammedFoysal , any ideas why it keeps producing the responses in a non-blocks kind of format. it just spits out text?

2024-07-16 13:02 UTC, MohammedFoysal approved these changes
Looks good. Don't forget to add summaries index name into ADO Library!

2024-07-17 09:09 UTC, StanHus commented
@MohammedFoysal added, ready to merge

2024-07-17 09:12 UTC, MohammedFoysal approved these changes

2024-07-17 09:12 UTC, merged